# Generated by Django 5.2.6 on 2025-09-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
