# Generated by Django 5.2.6 on 2025-09-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_study'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='name',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='name',
            new_name='session',
        ),
    ]
