# Generated by Django 5.2.6 on 2025-09-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_alter_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('session', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='study_files/')),
            ],
        ),
    ]
